function [fitresult, gof] = FourierFit(times, r,degree)
%CREATEFIT(TIMES,R)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : times
%      Y Output: r
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Mar-2015 14:11:54


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( times, r );
fitMethod = ['fourier',num2str(degree)];
% Set up fittype and options.
ft = fittype( fitMethod );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = zeros(1,2*(degree+1));% [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.00793331478179241];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'r vs. times', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'times' );
ylabel( 'r' );
grid on


